### ISSUE TITLE
ClassCastException when a `sort()` function returns a float

### ISSUE THREAD

**Issue by halfninja** [dynjs/dynjs#152]
I'm not sure if this is something DynJS _should_ handle or if code that does this is wrong, but a few Node modules return a non-integer result from a sort function and it does work as expected in other engines, so something to consider.

```
dynjs> ['25','10'].sort(function(a,b) { return parseFloat(b) - parseFloat(a); })
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
```

**Comment by lance** [comment]
Definitely a bug. I'll take a look.
